In [86]:
import pandas as pd
import os

# Example

In [87]:
max_val_f1 = df["val_f1"].max()
max_idx = df["val_f1"].idxmax()

print("Max val_f1:", max_val_f1)
print("ID:", max_idx)

Max val_f1: 0.6490796542073576
ID: 14

In [88]:
df = pd.read_csv("./BRONZE/ArchiveII_rnadist_200/telomerase/one-hot/metrics.csv")
print(df)

    train_loss  train_f1  val_loss    val_f1
0     0.078180  0.094062  0.038597  0.117807
1     0.051685  0.236911  0.034442  0.140022
2     0.046321  0.278124  0.033186  0.140349
3     0.044835  0.293542  0.032474  0.154825
4     0.043061  0.308421  0.032868  0.149473
5     0.043048  0.316804  0.033330  0.144283
6     0.042225  0.320727  0.032633  0.155309
7     0.041127  0.329565  0.032442  0.157299
8     0.041218  0.333692  0.033196  0.144147
9     0.040973  0.335977  0.033853  0.138105
10    0.040388  0.340342  0.032969  0.146505
11    0.040240  0.344136  0.032455  0.152370
12    0.039973  0.348991  0.033359  0.141761
13    0.039669  0.351996  0.033704  0.136212
14    0.039239  0.357096  0.033053  0.145714

# Pipeline

In [89]:
bronze = os.listdir("./BRONZE/")
bronze.sort()
bronze

['ArchiveII_famfold',
 'ArchiveII_hc_100',
 'ArchiveII_hc_200',
 'ArchiveII_hc_400',
 'ArchiveII_rnadist_100',
 'ArchiveII_rnadist_200',
 'ArchiveII_rnadist_400',
 'ArchiveII_samples_100',
 'ArchiveII_samples_200',
 'ArchiveII_samples_400']

In [90]:
fams = os.listdir("./BRONZE/ArchiveII_famfold/")
fams.sort()
fams

['16s', '23s', '5s', 'RNaseP', 'grp1', 'srp', 'tRNA', 'telomerase', 'tmRNA']

In [91]:
tables = {b[10:]: {fam: 999 for fam in fams} for b in bronze}
tables_id = {b[10:]: {fam: 999 for fam in fams} for b in bronze}

# Save OneHot encoded data

In [99]:
EMBEDDING = "one-hot"
for file in bronze:
    for fam in fams:
        data_path = f"./BRONZE/{file}/{fam}/{EMBEDDING}/metrics.csv"
        if os.path.exists(data_path):
            df = pd.read_csv(data_path)
            tables[file[10:]][fam] = df["val_f1"].max()
            tables_id[file[10:]][fam] = df["val_f1"].idxmax()
tables_df = pd.DataFrame(tables)
tables_id_df = pd.DataFrame(tables_id)

In [100]:
tables_df

,famfold,hc_100,hc_200,hc_400,rnadist_100,rnadist_200,rnadist_400,samples_100,samples_200,samples_400
16s,0.165955,0.176790,0.172565,0.171790,0.177671,0.175496,0.169992,0.171138,0.178608,0.177726
23s,0.217960,0.248963,0.254859,0.248073,0.238278,0.247058,0.246407,0.232445,0.231196,0.236537
5s,0.302964,0.274507,0.307439,0.323110,0.266982,0.287368,0.301740,0.285278,0.305465,0.307986
RNaseP,0.195204,0.231968,0.218198,0.218840,0.229668,0.222811,0.219416,0.225096,0.220527,0.213932
grp1,0.175828,0.191304,0.194980,0.193430,0.193354,0.192913,0.188268,0.188964,0.192502,0.190311
srp,0.177119,0.165824,0.174182,0.177704,0.174751,0.175871,0.175378,0.164127,0.175347,0.170907
tRNA,0.486793,0.374455,0.430655,0.464125,0.375334,0.443897,0.472553,0.438860,0.461141,0.476082
telomerase,0.129577,0.148743,0.146850,0.147367,0.146255,0.157299,0.145202,0.161353,0.143783,0.145757
tmRNA,0.179820,0.194391,0.206641,0.201923,0.202114,0.206749,0.201115,0.207295,0.208426,0.202421

In [94]:
tables_id_df

,famfold,hc_100,hc_200,hc_400,rnadist_100,rnadist_200,rnadist_400,samples_100,samples_200,samples_400
16s,4,9,9,7,12,6,2,12,13,5
23s,4,14,6,7,14,12,3,14,13,12
5s,13,13,12,10,13,13,13,14,8,7
RNaseP,4,12,13,8,10,14,8,14,9,7
grp1,5,11,9,10,14,10,3,10,8,2
srp,6,13,11,8,14,12,14,13,12,7
tRNA,2,11,11,5,13,9,12,9,11,6
telomerase,7,8,13,6,14,7,3,14,4,13
tmRNA,1,12,12,3,12,6,5,12,10,5

In [95]:
SAVE_PATH = "SILVER/test_tables"
os.makedirs(SAVE_PATH, exist_ok=True)
tables_df.to_csv(f"{SAVE_PATH}/OneHot_best_epochs_test.csv")
tables_id_df.to_csv(f"{SAVE_PATH}/OneHot_best_epochs_idx.csv")

# RiNALMo Encoding

In [96]:
EMBEDDING = "RiNALMo"
for file in bronze:
    for fam in fams:
        data_path = f"./BRONZE/{file}/{fam}/{EMBEDDING}/metrics.csv"
        if os.path.exists(data_path):
            df = pd.read_csv(data_path)
            max_val_f1 = df["val_f1"].max()
            max_idx = df["val_f1"].idxmax()
            tables[file[10:]][fam] = max_val_f1
            tables_id[file[10:]][fam] = max_idx
tables_df = pd.DataFrame(tables)
tables_id_df = pd.DataFrame(tables_id)

In [97]:
tables_df

,famfold,hc_100,hc_200,hc_400,rnadist_100,rnadist_200,rnadist_400,samples_100,samples_200,samples_400
16s,0.528892,0.441631,0.474158,0.525090,0.413338,0.474106,0.512192,0.432769,0.472590,0.563645
23s,0.606371,0.528655,0.550553,0.633745,0.517608,0.584345,0.595191,0.519056,0.582560,0.600184
5s,0.768991,0.746607,0.764104,0.777616,0.744527,0.755231,0.780014,0.779156,0.749145,0.759735
RNaseP,0.672326,0.559993,0.645640,0.631301,0.612839,0.648352,0.647001,0.589208,0.619332,0.634980
grp1,0.556711,0.521288,0.535939,0.556795,0.548789,0.558154,0.547126,0.507242,0.558426,0.579147
srp,0.594040,0.535034,0.593233,0.591578,0.552853,0.573320,0.577239,0.564554,0.574595,0.583805
tRNA,0.864434,0.844595,0.867271,0.875990,0.825141,0.858818,0.863043,0.841429,0.874955,0.862905
telomerase,0.112538,0.136816,0.129451,0.123962,0.125292,0.130671,0.138113,0.114192,0.113472,0.132021
tmRNA,0.637931,0.567253,0.625446,0.643279,0.570237,0.608031,0.658499,0.595996,0.627098,0.649080

In [98]:
SAVE_PATH = "SILVER/test_tables"
os.makedirs(SAVE_PATH, exist_ok=True)
tables_df.to_csv(f"{SAVE_PATH}/RiNALMo_best_epochs_test.csv")
tables_id_df.to_csv(f"{SAVE_PATH}/RiNALMo_best_epochs_idx.csv")