In [1]:
import pandas as pd
import os

# Example

In [2]:
df = pd.read_csv("./BRONZE/ArchiveII_rnadist_200/telomerase/one-hot/metrics.csv")
print(df)

    train_loss  train_f1  val_loss    val_f1
0     0.086863  0.085744  0.037821  0.099971
1     0.044944  0.232164  0.033570  0.140927
2     0.041069  0.275803  0.032698  0.144409
3     0.039373  0.294999  0.032254  0.144772
4     0.037629  0.308741  0.032143  0.145553
5     0.037120  0.319024  0.032829  0.139505
6     0.036714  0.325963  0.032187  0.148628
7     0.036325  0.333452  0.032422  0.144842
8     0.035488  0.342258  0.033358  0.138078
9     0.034998  0.350133  0.032677  0.146936
10    0.034753  0.353135  0.033936  0.131154
11    0.033854  0.358211  0.032454  0.149245
12    0.033421  0.367470  0.033176  0.141625
13    0.032449  0.373704  0.033505  0.136314
14    0.032379  0.377231  0.033386  0.141232

In [3]:
last_val_f1 = df["val_f1"].iloc[-1]

print("Max val_f1:", last_val_f1)

Max val_f1: 0.1412324711137439

# Pipeline

In [4]:
bronze = os.listdir("./BRONZE/")
bronze.sort()
del bronze[1]  # ref
bronze

['ArchiveII_famfold',
 'ArchiveII_hc_100',
 'ArchiveII_hc_200',
 'ArchiveII_hc_400',
 'ArchiveII_rnadist_100',
 'ArchiveII_rnadist_200',
 'ArchiveII_rnadist_400',
 'ArchiveII_samples_100',
 'ArchiveII_samples_200',
 'ArchiveII_samples_400',
 'over_sampled']

In [5]:
fams = os.listdir("./BRONZE/ArchiveII_famfold/")
fams.sort()
fams

['16s', '23s', '5s', 'RNaseP', 'grp1', 'srp', 'tRNA', 'telomerase', 'tmRNA']

In [6]:
tables = {b[10:]: {fam: 999 for fam in fams} for b in bronze}

# Save OneHot encoded data

In [7]:
EMBEDDING = "one-hot"
for file in bronze:
    for fam in fams:
        data_path = f"./BRONZE/over_sampled/{file}/{fam}/{EMBEDDING}/metrics.csv"
        if os.path.exists(data_path):
            df = pd.read_csv(data_path)
            tables[file[10:]][fam] = df["val_f1"].iloc[-1]
tables_df = pd.DataFrame(tables)

In [8]:
tables_df

,famfold,hc_100,hc_200,hc_400,rnadist_100,rnadist_200,rnadist_400,samples_100,samples_200,samples_400,ed
16s,0.152518,0.172197,0.157070,0.161667,0.175516,0.161488,0.152830,0.157428,0.168292,0.150432,999
23s,0.209476,0.238470,0.229374,0.210526,0.238900,0.226427,0.218092,0.216545,0.206449,0.212792,999
5s,0.281220,0.274444,0.270932,0.250319,0.275964,0.260469,0.271124,0.264378,0.283033,0.266354,999
RNaseP,0.183204,0.227642,0.223183,0.195662,0.231432,0.224089,0.211692,0.229750,0.211530,0.206190,999
grp1,0.166082,0.202688,0.177929,0.178124,0.190577,0.187289,0.179173,0.189766,0.180934,0.168627,999
srp,0.165332,0.149521,0.160955,0.153915,0.171547,0.158514,0.159889,0.156458,0.154297,0.147969,999
tRNA,0.465288,0.360006,0.351069,0.411297,0.394705,0.377940,0.366556,0.356754,0.372652,0.345818,999
telomerase,0.114144,0.145224,0.150747,0.097737,0.151355,0.141232,0.118632,0.126115,0.126954,0.112975,999
tmRNA,0.167492,0.199917,0.191287,0.174441,0.194878,0.197681,0.180009,0.199479,0.183526,0.175488,999

In [9]:
SAVE_PATH = "SILVER/test_tables_ov"
os.makedirs(SAVE_PATH, exist_ok=True)
tables_df.to_csv(f"{SAVE_PATH}/OneHot_15_epochs_test.csv")

# RiNALMo Encoding

In [10]:
EMBEDDING = "RiNALMo"
for file in bronze:
    for fam in fams:
        data_path = f"./BRONZE/over_sampled/{file}/{fam}/{EMBEDDING}/metrics.csv"
        if os.path.exists(data_path):
            df = pd.read_csv(data_path)
            tables[file[10:]][fam] = df["val_f1"].iloc[-1]
tables_df = pd.DataFrame(tables)

In [11]:
tables_df

,famfold,hc_100,hc_200,hc_400,rnadist_100,rnadist_200,rnadist_400,samples_100,samples_200,samples_400,ed
16s,0.509853,0.449643,0.456522,0.507755,0.458332,0.483743,0.471323,0.497973,0.474495,0.524779,999
23s,0.573340,0.555562,0.590465,0.612669,0.543431,0.610788,0.573751,0.576566,0.614452,0.585411,999
5s,0.739421,0.736565,0.742397,0.754717,0.763655,0.759168,0.766680,0.736381,0.731653,0.770101,999
RNaseP,0.653999,0.598952,0.647175,0.664833,0.622862,0.643215,0.625388,0.627342,0.623998,0.629984,999
grp1,0.474777,0.527685,0.554909,0.530461,0.497354,0.537117,0.552484,0.519098,0.532908,0.558371,999
srp,0.586522,0.560204,0.569028,0.560013,0.546887,0.554820,0.581424,0.558890,0.566529,0.580530,999
tRNA,0.835476,0.844458,0.847748,0.876568,0.864766,0.869474,0.874792,0.850126,0.863674,0.884302,999
telomerase,0.090693,0.103562,0.100338,0.082634,0.104234,0.132905,0.097518,0.084793,0.103108,0.079993,999
tmRNA,0.620926,0.553526,0.625165,0.654962,0.579667,0.596219,0.658855,0.608152,0.618772,0.628193,999

In [12]:
SAVE_PATH = "SILVER/test_tables_ov"
os.makedirs(SAVE_PATH, exist_ok=True)
tables_df.to_csv(f"{SAVE_PATH}/RiNALMo_15_epochs_test.csv")

# make ref table

In [13]:
embeddings = ["one-hot", "RiNALMo"]

In [14]:
tables = {emb: {fam: 999 for fam in fams} for emb in embeddings}

for EMBEDDING in embeddings:
    for fam in fams:
        data_path = f"./BRONZE/ArchiveII_famfold_ref/{EMBEDDING}/{fam}/metrics.csv"
        if os.path.exists(data_path):
            df = pd.read_csv(data_path)
            tables[EMBEDDING][fam] = df["test_f1"].iloc[-1]
    tables_df = pd.DataFrame(tables)

In [15]:
tables_df

             one-hot   RiNALMo
16s         0.163151  0.464055
23s         0.204189  0.580163
5s          0.282241  0.791958
RNaseP      0.170795  0.649099
grp1        0.156658  0.555685
srp         0.174403  0.541768
tRNA        0.448521  0.841117
telomerase  0.118064  0.087954
tmRNA       0.162696  0.658737

In [16]:
SAVE_PATH = "SILVER/test_tables"
os.makedirs(SAVE_PATH, exist_ok=True)
tables_df.to_csv(f"{SAVE_PATH}/ref_15_epochs.csv")