In [13]:
import pandas as pd
import os

# Example

In [14]:
df = pd.read_csv("./BRONZE/ArchiveII_rnadist_200/telomerase/one-hot/metrics.csv")
print(df)

    train_loss  train_f1  val_loss    val_f1
0     0.078180  0.094062  0.038597  0.117807
1     0.051685  0.236911  0.034442  0.140022
2     0.046321  0.278124  0.033186  0.140349
3     0.044835  0.293542  0.032474  0.154825
4     0.043061  0.308421  0.032868  0.149473
5     0.043048  0.316804  0.033330  0.144283
6     0.042225  0.320727  0.032633  0.155309
7     0.041127  0.329565  0.032442  0.157299
8     0.041218  0.333692  0.033196  0.144147
9     0.040973  0.335977  0.033853  0.138105
10    0.040388  0.340342  0.032969  0.146505
11    0.040240  0.344136  0.032455  0.152370
12    0.039973  0.348991  0.033359  0.141761
13    0.039669  0.351996  0.033704  0.136212
14    0.039239  0.357096  0.033053  0.145714

In [15]:
last_val_f1 = df["val_f1"].iloc[-1]

print("Max val_f1:", last_val_f1)

Max val_f1: 0.1457144067968711

# Pipeline

In [16]:
bronze = os.listdir("./BRONZE/")
bronze.sort()
del bronze[1]  # ref
bronze

['ArchiveII_famfold',
 'ArchiveII_hc_100',
 'ArchiveII_hc_200',
 'ArchiveII_hc_400',
 'ArchiveII_rnadist_100',
 'ArchiveII_rnadist_200',
 'ArchiveII_rnadist_400',
 'ArchiveII_samples_100',
 'ArchiveII_samples_200',
 'ArchiveII_samples_400']

In [17]:
fams = os.listdir("./BRONZE/ArchiveII_famfold/")
fams.sort()
fams

['16s', '23s', '5s', 'RNaseP', 'grp1', 'srp', 'tRNA', 'telomerase', 'tmRNA']

In [18]:
tables = {b[10:]: {fam: 999 for fam in fams} for b in bronze}

# Save OneHot encoded data

In [19]:
EMBEDDING = "one-hot"
for file in bronze:
    for fam in fams:
        data_path = f"./BRONZE/{file}/{fam}/{EMBEDDING}/metrics.csv"
        if os.path.exists(data_path):
            df = pd.read_csv(data_path)
            tables[file[10:]][fam] = df["val_f1"].iloc[-1]
tables_df = pd.DataFrame(tables)

In [20]:
tables_df

,famfold,hc_100,hc_200,hc_400,rnadist_100,rnadist_200,rnadist_400,samples_100,samples_200,samples_400
16s,0.152518,0.176533,0.171753,0.154954,0.174203,0.170744,0.165594,0.156720,0.163572,0.160037
23s,0.209476,0.248963,0.238251,0.234266,0.238278,0.221297,0.209013,0.232445,0.222398,0.218396
5s,0.281220,0.268053,0.279704,0.297100,0.228899,0.248058,0.278214,0.285278,0.260221,0.290877
RNaseP,0.183204,0.227096,0.216515,0.208379,0.227091,0.222811,0.204182,0.225096,0.207151,0.195743
grp1,0.166082,0.188171,0.190160,0.178886,0.193354,0.186702,0.174508,0.186899,0.174148,0.189761
srp,0.165332,0.156927,0.169713,0.161831,0.174751,0.171980,0.175378,0.157963,0.166569,0.168871
tRNA,0.465288,0.369919,0.427000,0.438360,0.326411,0.435446,0.433944,0.366606,0.428908,0.426321
telomerase,0.114144,0.136152,0.140468,0.145162,0.146255,0.145714,0.121199,0.161353,0.127018,0.117748
tmRNA,0.167492,0.194175,0.203543,0.198519,0.196188,0.200216,0.184736,0.202698,0.200101,0.183869

In [21]:
SAVE_PATH = "SILVER/test_tables"
os.makedirs(SAVE_PATH, exist_ok=True)
tables_df.to_csv(f"{SAVE_PATH}/OneHot_15_epochs_test.csv")

# RiNALMo Encoding

In [22]:
EMBEDDING = "RiNALMo"
for file in bronze:
    for fam in fams:
        data_path = f"./BRONZE/{file}/{fam}/{EMBEDDING}/metrics.csv"
        if os.path.exists(data_path):
            df = pd.read_csv(data_path)
            tables[file[10:]][fam] = df["val_f1"].iloc[-1]
tables_df = pd.DataFrame(tables)

In [23]:
tables_df

,famfold,hc_100,hc_200,hc_400,rnadist_100,rnadist_200,rnadist_400,samples_100,samples_200,samples_400
16s,0.509853,0.441631,0.458123,0.520438,0.413338,0.462140,0.456747,0.421239,0.459383,0.552313
23s,0.573340,0.517211,0.534760,0.611863,0.496194,0.578091,0.579155,0.519056,0.563238,0.597884
5s,0.739421,0.746607,0.763970,0.768595,0.730811,0.744533,0.763696,0.775930,0.745209,0.749873
RNaseP,0.653999,0.559993,0.645640,0.624507,0.612839,0.633260,0.619183,0.589208,0.603671,0.587982
grp1,0.474777,0.511049,0.527383,0.546749,0.540281,0.558154,0.544809,0.483329,0.519261,0.540803
srp,0.586522,0.530609,0.573562,0.583741,0.546316,0.559678,0.572559,0.561299,0.565040,0.554591
tRNA,0.835476,0.844595,0.867271,0.867267,0.825141,0.851912,0.863043,0.841429,0.874955,0.853181
telomerase,0.090693,0.136816,0.101971,0.089344,0.125292,0.121063,0.102304,0.083072,0.094594,0.097243
tmRNA,0.620926,0.549949,0.616359,0.630807,0.570237,0.606862,0.656603,0.594807,0.606080,0.649080

In [24]:
SAVE_PATH = "SILVER/test_tables"
os.makedirs(SAVE_PATH, exist_ok=True)
tables_df.to_csv(f"{SAVE_PATH}/RiNALMo_15_epochs_test.csv")

# make ref table

In [25]:
embeddings = ["one-hot", "RiNALMo"]

In [26]:
tables = {emb: {fam: 999 for fam in fams} for emb in embeddings}

for EMBEDDING in embeddings:
    for fam in fams:
        data_path = f"./BRONZE/ArchiveII_famfold_ref/{EMBEDDING}/{fam}/metrics.csv"
        if os.path.exists(data_path):
            df = pd.read_csv(data_path)
            tables[EMBEDDING][fam] = df["test_f1"].iloc[-1]
    tables_df = pd.DataFrame(tables)

In [27]:
tables_df

             one-hot   RiNALMo
16s         0.163151  0.464055
23s         0.204189  0.580163
5s          0.282241  0.791958
RNaseP      0.170795  0.649099
grp1        0.156658  0.555685
srp         0.174403  0.541768
tRNA        0.448521  0.841117
telomerase  0.118064  0.087954
tmRNA       0.162696  0.658737

In [28]:
SAVE_PATH = "SILVER/test_tables"
os.makedirs(SAVE_PATH, exist_ok=True)
tables_df.to_csv(f"{SAVE_PATH}/ref_15_epochs.csv")