In [17]:
import pandas as pd
import os

# Example

In [18]:
DATA_ROOT = "./BRONZE/over_sampled_w_valid20/"
df = pd.read_csv(
    DATA_ROOT + "ArchiveII_rnadist_200/telomerase/one-hot/metrics_test.csv"
)
print(df)

   test_loss   test_f1
0   0.033568  0.142394

In [19]:
test_f1 = df["test_f1"].iloc[-1]

print("Max test_f1:", test_f1)

Max test_f1: 0.1423940365607267

# Pipeline

In [20]:
bronze = os.listdir(DATA_ROOT)
bronze.sort()
# del bronze[1]  # ref
bronze

['ArchiveII_famfold',
 'ArchiveII_hc_100',
 'ArchiveII_hc_200',
 'ArchiveII_hc_400',
 'ArchiveII_rnadist_100',
 'ArchiveII_rnadist_200',
 'ArchiveII_rnadist_400',
 'ArchiveII_samples_100',
 'ArchiveII_samples_200',
 'ArchiveII_samples_400']

In [21]:
fams = os.listdir(DATA_ROOT + "ArchiveII_famfold/")
fams.sort()
fams

['16s', '23s', '5s', 'RNaseP', 'grp1', 'srp', 'tRNA', 'telomerase', 'tmRNA']

In [22]:
tables = {b[10:]: {fam: 999 for fam in fams} for b in bronze}

# Save OneHot encoded data

In [23]:
EMBEDDING = "one-hot"
for file in bronze:
    if file == "ArchiveII_famfold":
        for fam in fams:
            data_path = DATA_ROOT + f"{file}/{fam}/{EMBEDDING}/metrics.csv"
            if os.path.exists(data_path):
                df = pd.read_csv(data_path)
                tables[file[10:]][fam] = df["val_f1"].iloc[-1]
    else:
        for fam in fams:
            data_path = DATA_ROOT + f"{file}/{fam}/{EMBEDDING}/metrics_test.csv"
            if os.path.exists(data_path):
                df = pd.read_csv(data_path)
                tables[file[10:]][fam] = df["test_f1"].iloc[-1]
tables_df = pd.DataFrame(tables)

In [24]:
tables_df

,famfold,hc_100,hc_200,hc_400,rnadist_100,rnadist_200,rnadist_400,samples_100,samples_200,samples_400
16s,0.152518,0.165647,0.170648,0.164711,0.172321,0.172063,0.159586,0.173679,0.171130,0.153062
23s,0.209476,0.238901,0.233489,0.205994,0.245580,0.227753,0.205827,0.206960,0.214750,0.213082
5s,0.281220,0.283302,0.275457,0.250736,0.241849,0.248317,0.267937,0.258017,0.250762,0.263742
RNaseP,0.183204,0.222964,0.205807,0.210350,0.229600,0.221200,0.206054,0.234030,0.221594,0.201759
grp1,0.166082,0.190808,0.180444,0.181166,0.179180,0.188336,0.176761,0.179401,0.189395,0.189251
srp,0.165332,0.139832,0.147569,0.156721,0.149768,0.161466,0.143897,0.148482,0.157047,0.133513
tRNA,0.465288,0.333238,0.381570,0.390417,0.383106,0.397043,0.364986,0.355539,0.386568,0.372797
telomerase,0.114144,0.141106,0.139602,0.135177,0.144303,0.142394,0.125742,0.126732,0.120201,0.138780
tmRNA,0.167492,0.196592,0.201813,0.168256,0.193758,0.204948,0.182499,0.199256,0.186098,0.180544

In [25]:
SAVE_PATH = "SILVER/test_tables_ov"
os.makedirs(SAVE_PATH, exist_ok=True)
tables_df.to_csv(f"{SAVE_PATH}/OneHot_val20_15_epochs_test.csv")

# RiNALMo Encoding

In [26]:
EMBEDDING = "RiNALMo"
for file in bronze:
    if file == "ArchiveII_famfold":
        for fam in fams:
            data_path = DATA_ROOT + f"{file}/{fam}/{EMBEDDING}/metrics.csv"
            if os.path.exists(data_path):
                df = pd.read_csv(data_path)
                tables[file[10:]][fam] = df["val_f1"].iloc[-1]
    else:
        for fam in fams:
            data_path = DATA_ROOT + f"{file}/{fam}/{EMBEDDING}/metrics_test.csv"
            if os.path.exists(data_path):
                df = pd.read_csv(data_path)
                tables[file[10:]][fam] = df["test_f1"].iloc[-1]
tables_df = pd.DataFrame(tables)

In [27]:
tables_df

,famfold,hc_100,hc_200,hc_400,rnadist_100,rnadist_200,rnadist_400,samples_100,samples_200,samples_400
16s,0.509853,0.480309,0.504731,0.505145,0.458192,0.495003,0.477525,0.485068,0.469235,0.493967
23s,0.573340,0.556551,0.584800,0.620886,0.526856,0.600022,0.614504,0.593622,0.580956,0.602602
5s,0.739421,0.741980,0.758109,0.770009,0.713456,0.758205,0.775638,0.712794,0.676934,0.754466
RNaseP,0.653999,0.593268,0.646212,0.640336,0.589957,0.636697,0.663149,0.605855,0.620496,0.630230
grp1,0.474777,0.536684,0.494429,0.555306,0.482075,0.543685,0.556137,0.511188,0.509338,0.542711
srp,0.586522,0.547674,0.551228,0.580122,0.549019,0.531469,0.583190,0.551670,0.555714,0.591854
tRNA,0.835476,0.855418,0.864722,0.861802,0.825414,0.832716,0.855405,0.860813,0.862959,0.866797
telomerase,0.090693,0.109265,0.097837,0.098872,0.099375,0.098960,0.102459,0.083427,0.068878,0.108823
tmRNA,0.620926,0.564861,0.607493,0.628625,0.552721,0.593302,0.640032,0.608832,0.611575,0.590897

In [28]:
SAVE_PATH = "SILVER/test_tables_ov"
os.makedirs(SAVE_PATH, exist_ok=True)
tables_df.to_csv(f"{SAVE_PATH}/RiNALMo_val20_15_epochs_test.csv")

# make ref table

In [13]:
embeddings = ["one-hot", "RiNALMo"]

In [14]:
tables = {emb: {fam: 999 for fam in fams} for emb in embeddings}

for EMBEDDING in embeddings:
    for fam in fams:
        data_path = f"./BRONZE/ArchiveII_famfold_ref/{EMBEDDING}/{fam}/metrics.csv"
        if os.path.exists(data_path):
            df = pd.read_csv(data_path)
            tables[EMBEDDING][fam] = df["test_f1"].iloc[-1]
    tables_df = pd.DataFrame(tables)

In [15]:
tables_df

             one-hot   RiNALMo
16s         0.163151  0.464055
23s         0.204189  0.580163
5s          0.282241  0.791958
RNaseP      0.170795  0.649099
grp1        0.156658  0.555685
srp         0.174403  0.541768
tRNA        0.448521  0.841117
telomerase  0.118064  0.087954
tmRNA       0.162696  0.658737

In [16]:
SAVE_PATH = "SILVER/test_tables"
os.makedirs(SAVE_PATH, exist_ok=True)
tables_df.to_csv(f"{SAVE_PATH}/ref_15_epochs.csv")